// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDbJoIBR1YCuhF90iN73Rxc2DDCtDThjc',
    appId: '1:543806373604:web:eff05afe755e7ece8436f1',
    messagingSenderId: '543806373604',
    projectId: 'budget-manager-revamped',
    authDomain: 'budget-manager-revamped.firebaseapp.com',
    storageBucket: 'budget-manager-revamped.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoBdHhkVVN95lSi9DikoEwvu4K0oAjqfY',
    appId: '1:543806373604:android:0133f39e0ff5f7cc8436f1',
    messagingSenderId: '543806373604',
    projectId: 'budget-manager-revamped',
    storageBucket: 'budget-manager-revamped.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJDDA1H6v90fyi6pkpDsI9nZtkKKD37q8',
    appId: '1:543806373604:ios:0ce8543910fa0a498436f1',
    messagingSenderId: '543806373604',
    projectId: 'budget-manager-revamped',
    storageBucket: 'budget-manager-revamped.appspot.com',
    androidClientId: '543806373604-13v1g857muu1vpjje5sv74k5bjpr45mh.apps.googleusercontent.com',
    iosClientId: '543806373604-4r29ole0p5r8v026vkmc8oj6u6lqakq5.apps.googleusercontent.com',
    iosBundleId: 'com.princeakash.budgetManagerRevamped',
  );
}
